### ISSUE TITLE
Auto style cartography checklist

### ISSUE THREAD

**Issue by fdansv** [CartoDB/deep-insights.js#344]
This list is for self-reference, checks mean I've internally implemented the item, not that it's been merged or even committed.

#### Prerequisites:
* [x] Autostyle base functionality #304
* [x] Jenks https://github.com/CartoDB/d3.cartodb/pull/181
* [x] Heads/Tails https://github.com/CartoDB/d3.cartodb/pull/182
* [x] Distribution type calculation https://github.com/CartoDB/cartodb.js/pull/1256
* [x] Cartocolor support in turbo-carto https://github.com/CartoDB/turbo-carto/pull/19
* [ ] Histogram cluster detection
* [x] Styling based on basemap

#### From histogram:
**Points**
* [ ] Sized by value #327
* [x] Colored - J&L #328
* [x] Colored - F #330 
* [x] Colored - C #329
* [x] Colored - A #332 

**Polygons**
* [x] F #346 
* [x] C #348 
* [x] A #345
* [x] J&L #347

#### From category:
* [x] Points #326 
* [x] Polygons #331 

#### Extras:
* [ ] Compound auto styling (histogram + category on same layer) #341 

@javisantana @makella

**Comment by makella** [comment]
@fdansv this is great!

One note, for the Polygon > F I used a different color ramp than the points. Every other distribution is the same for points and polygons.

**Comment by makella** [comment]
@fdansv i owe you lines!! will be in the issues soon

**Comment by fdansv** [comment]
I'm closing issues whose tasks have been completed

**Comment by fdansv** [comment]
I feel like this checklist has done its job, let's rely on separate issues for pending tasks related to autostyling.
